repos:
 - repo: https://github.com/Quantco/pre-commit-mirrors-black
   rev: 23.3.0
   hooks:
     - id: black-conda
 - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
   rev: 6.0.0
   hooks:
    - id: flake8-conda
 - repo: https://github.com/Quantco/pre-commit-mirrors-isort
   rev: 5.12.0
   hooks:
    - id: isort-conda
      additional_dependencies: [toml]
      args: ["--profile", "black"]
 - repo: https://github.com/Quantco/pre-commit-mirrors-mypy
   rev: "1.2.0"
   hooks:
    - id: mypy-conda
      additional_dependencies: [-c, conda-forge, types-setuptools]
 - repo: https://github.com/Quantco/pre-commit-mirrors-pyupgrade
   rev: 3.4
   hooks:
    - id: pyupgrade-conda
      args:
        - --py39-plus
