name: turbodbc
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pyarrow>=1.0,<11
  - unixodbc  # [unix]
  - c-compiler
  - cxx-compiler
  - gmock=1.10.0
  - gtest
  - boost
  - cmake
  - ninja
  - pytest
  - numpy
  - pybind11
