name: turbodbc
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pyarrow>=1.0,<11
  - unixodbc
  - c-compiler
  - cxx-compiler
  - boost
  - cmake
  - ninja
  - pytest
  - numpy
  - pybind11
